### ISSUE TITLE
net8 issues

### ISSUE THREAD

**Issue by tatweertech** [RadekVyM/Navbar-Animation-1#5]
not working with net8.
try to change framework to net8 not UI showing

**Comment by abdel-moumen-abdel-raouf** [comment]
Any updates?

**Comment by RadekVyM** [comment]
Hi, I have updated the project to .NET 8 and it is working now.

**Comment by abdel-moumen-abdel-raouf** [comment]
> Hi, I have updated the project to .NET 8 and it is working now.

Great, Will test it, Thanks :)
